export const IMMUTABLE_TEST_REQUEST = 'IMMUTABLE_TEST_REQUEST';
export const IMMUTABLE_TEST_SUCCESS = 'IMMUTABLE_TEST_SUCCESS';
export const IMMUTABLE_TEST_FAILED = 'IMMUTABLE_TEST_FAILED';

export const HOME_TEST_REQUEST = 'HOME_TEST_REQUEST';
export const HOME_TEST_SUCCESS = 'HOME_TEST_SUCCESS';
export const HOME_TEST_FAILED = 'HOME_TEST_FAILED';